### PR TITLE
Designs a new "fsTeardown" API

### PR DESCRIPTION
**Pull request by kettanaito**
This is a breaking change.
- Related to #1 

## Motivation

- Allow creating more complex file structures with less API clutter.
- Support runtime file/directory creation, so that each individual suit could create its own tree structure. The API is designed to be used globally, not in each test.
- Support resetting the entire mock base directory between tests.

## Breaking changes

- `createTeardown` is renamed to `fsTeardown` to be aligned with the package's name.
- `.getPath` is renamed to `.resolve` to be aligned with `path.resolve`.
- `.addFile` was replaced with `.create` that allows creating files and directories.
- Adds a new `.reset()` method that restores the directory to its initial state (`paths` from the `fsTeardown` call).

### CODE REVIEW

**Comment by kettanaito** [comment]
Hey, @nzakas. I'd like to re-design the public API of this library and wanted to ask your opinion on the proposed changes. You can find the updated README on this feature branch. Thank you.

**Review by nzakas — APPROVED** [review]
I like it! Nice work.

**Comment by kettanaito** [comment]
I wonder if `.prepare()` is an intuitive method name to instantiate the mocks. My worry is that people will confuse it with `.create()` that has a similar meaning. 

Some alternatives to `.prepare()`:

- `init`
- `mock`
- `emit`
- `write`

**Comment by nzakas** [comment]
I think prepare is fine, but if you want to be explicit, you could use writeToDisk.

**Comment by kettanaito** [comment]
Agreed. I'll keep `.prepare` and `.create` and see whether the usage will suggest some changes. Thank you, Nicholas!

**Comment by kettanaito** [comment]
@nzakas, if you need help updating ESLint with these changes just let me know. I may need a quick intro to your custom setup to migrate it efficiently.

**Comment by nzakas** [comment]
We likely won’t update the tests, as they are working fine right now, but if you’d like to try doing it yourself, please feel free.

**Pull request merged**
